# Generated by Django 2.1.1 on 2018-09-25 17:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
                ('update_date_time', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('create_date_time', models.DateTimeField(auto_now=True, verbose_name='update date')),
            ],
        ),
    ]
